### PR TITLE
docs: new rippling compatibility for API

### PR DESCRIPTION
**Pull request by alexromano**
switching to API token compatibility for rippling

### CODE REVIEW

**Review by seii — COMMENTED** [review]
@alexromano I'm only seeing Company, Individual, Employment, and Pay Statement updated here. What about Directory and Payment?

**Comment by alexromano** [comment]
@seii they are teh same

**Comment by seii** [comment]
@alexromano Wouldn't we want Rippling to have the `(API)` designator now? If we have any plans to pursue alternative approaches, we would pretty quickly end up with two Rippling entries anyway.

**Comment by alexromano** [comment]
@seii  No, the (API) mark is only to distinguish between auth methods when providers have more than one. In this case there is only one option. If we add the other method back, we will mark this column with (API)

**Review by seii — APPROVED** [review]
Approved

**Pull request merged**
