### PR TITLE
add ACF SLAs

### PR DESCRIPTION
**Pull request by alexromano**

### CODE REVIEW

**Comment by alexromano** [comment]
Screen Shot 2022-09-30 at 4 18 11 PM
Screen Shot 2022-09-30 at 4 18 42 PM

**Comment by seii** [comment]
@alexromano We probably want to decide on either "Pay Ready" or "pay-enabled" so we use one term. Any favorites?

**Comment by alexromano** [comment]
updated to pay enabled.

**Comment by alexromano** [comment]
@seii updated to enabled

**Review by seii — APPROVED** [review]
Approved

**Pull request merged**
