### PR TITLE
add register benefit endpoint

### PR DESCRIPTION
**Pull request by vitorfreitas**

### CODE REVIEW

**Comment by StephenGrable1** [comment]
[Stoplight proposal link ](https://tryfinch.stoplight.io/proposals/reference/branches/u%2Fvitorfreitas%2Fregister-benefit-endpoint)

**Review by ananyabanthia — APPROVED** [review]
Looks good; the one thing I would add is a sentence similar to after the "Please use the /provider endpoint..." in the intro

 "If successfully registered, the resulting benefit_id can be used to manage employee deductions going forward."

**Review by alexromano — APPROVED** [review]

**Review by ananyabanthia — APPROVED** [review]

**Comment by alexromano** [comment]
@ananyabanthia should we merge or close this? been open 2mo

**Comment by ananyabanthia** [comment]
@alexromano this endpoint might end up changing so we should just close this one, and either re-open (if nothing changes) or create a new PR with the new details when those are finalized

**Pull request closed without merging**
