### PR TITLE
Update open.yml

### PR DESCRIPTION
**Pull request by StephenGrable1**
Match updates in https://github.com/Finch-API/finch-openapi/pull/17/files

### CODE REVIEW

**Comment by alexromano** [comment]
Screen Shot 2023-03-16 at 10 00 57 AM
this is how it looks today

**Comment by alexromano** [comment]
Screen Shot 2023-04-05 at 2 01 43 PM
this is how it looks today

**Comment by StephenGrable1** [comment]
> Screen Shot 2023-04-05 at 2 01 43 PM
> 
> this is how it looks today

the goal is to correct the syntax to follow openapi spec - what we have now is actually invalid - via the openapi docs [here](https://swagger.io/docs/specification/data-models/data-types/#type) - what we have now is still valid json schema which explains why it might still render 

> Screen Shot 2023-04-05 at 2 00 11 PM
> 

does this drop-down show all the valid values? since we're using open api spec, we should lean toward adhering to the spec - we can also look into upgrading to v3.1 soon, since that might improve the readability in spotlight

**Comment by alexromano** [comment]
the value of the docs are in UX/readability over conforming to the spec. if we moved off of stoplight or had control over how this was rendered, I would say go for it, but until that's the case we should err on the side of consistency (this is how all of our multi-type responses look across the API) and readability

**Comment by StephenGrable1** [comment]
@alexromano that makes sense, thanks for the explanation - ill go ahead and close this

**Pull request closed without merging**
